# Generated by Django 3.1.4 on 2021-01-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VEH', 'Vehicle'), ('LOC', 'Location')], default='VEH', max_length=3)),
                ('steam_id', models.IntegerField(blank=True, default=0)),
                ('component_version', models.TextField(default='1.0')),
                ('component_name', models.TextField(default='Example_Mod')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.TextField(default='')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webgui.component')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField(default='Example Team')),
                ('vehicle_number', models.IntegerField(default=1)),
                ('short_name', models.TextField(default='')),
                ('do_update', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webgui.component')),
            ],
        ),
    ]
