# Generated by Django 3.1.4 on 2021-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overwrites_multiplayer', models.TextField(default='{}')),
                ('overwrites_player', models.TextField(default='{}')),
                ('name', models.TextField(default='')),
                ('version', models.TextField(default='')),
                ('rfm', models.FileField(upload_to='')),
            ],
        ),
    ]
