# Generated by Django 3.1.4 on 2021-01-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0002_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfm', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='rfm',
        ),
        migrations.AddField(
            model_name='server',
            name='conditions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='webgui.raceconditions'),
            preserve_default=False,
        ),
    ]
