# Generated by Django 3.1.4 on 2021-01-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0003_auto_20210103_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='entries',
            field=models.ManyToManyField(to='webgui.Entry'),
        ),
    ]
