# Generated by Django 3.1.4 on 2021-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0004_server_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceconditions',
            name='description',
            field=models.TextField(default='Add description'),
        ),
    ]
