# Generated by Django 3.1.4 on 2021-01-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0006_server_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_name',
            field=models.CharField(default='Example_Mod', max_length=200),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='short_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='team_name',
            field=models.CharField(default='Example Team', max_length=200),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='server',
            name='version',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='layout',
            field=models.CharField(default='', max_length=200),
        ),
    ]
