# Generated by Django 3.1.4 on 2021-01-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0007_auto_20210103_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='do_update',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='short_name',
        ),
        migrations.AddField(
            model_name='component',
            name='do_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='short_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
