# Generated by Django 3.1.4 on 2021-01-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0008_auto_20210106_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='version',
        ),
    ]
