# Generated by Django 3.1.4 on 2021-01-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0009_remove_server_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='server',
            name='entries',
        ),
        migrations.RemoveField(
            model_name='server',
            name='name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='overwrites_multiplayer',
        ),
        migrations.RemoveField(
            model_name='server',
            name='overwrites_player',
        ),
        migrations.RemoveField(
            model_name='server',
            name='tracks',
        ),
        migrations.AddField(
            model_name='server',
            name='build_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='packs_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='public_ip',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='secret',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overwrites_multiplayer', models.TextField(default='{}')),
                ('overwrites_player', models.TextField(default='{}')),
                ('name', models.CharField(default='', max_length=200)),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webgui.raceconditions')),
                ('entries', models.ManyToManyField(to='webgui.Entry')),
                ('tracks', models.ManyToManyField(to='webgui.Track')),
            ],
        ),
    ]
