# Generated by Django 3.1.4 on 2021-01-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0011_server_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('OFF', 'Stopped'), ('S+', 'Start requested'), ('R', 'Running'), ('R-', 'Stop requested')], default='OFF', max_length=3),
        ),
    ]
