# Generated by Django 3.1.4 on 2021-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0012_server_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
        migrations.AddField(
            model_name='server',
            name='action',
            field=models.CharField(choices=[('OFF', 'Stopped'), ('S+', 'Start requested'), ('R', 'Running'), ('R-', 'Stop requested'), ('D', 'Change config')], default='OFF', max_length=3),
        ),
    ]
