# Generated by Django 3.1.4 on 2021-01-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0013_auto_20210108_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start requested'), ('R-', 'Stop requested'), ('D', 'Change config')], default='', max_length=3),
        ),
    ]
