# Generated by Django 3.1.4 on 2021-01-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0014_auto_20210108_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Change config')], default='', max_length=3),
        ),
    ]
