# Generated by Django 3.1.4 on 2021-01-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0015_auto_20210108_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='files',
            field=models.ManyToManyField(to='webgui.EntryFile'),
        ),
    ]
