# Generated by Django 3.1.4 on 2021-01-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0016_auto_20210108_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='files',
        ),
    ]
