# Generated by Django 3.1.4 on 2021-01-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0017_remove_entry_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tracks',
            field=models.ManyToManyField(to='webgui.EntryFile'),
        ),
    ]
