# Generated by Django 3.1.4 on 2021-01-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0018_entry_tracks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='tracks',
            new_name='files',
        ),
    ]
