# Generated by Django 3.1.4 on 2021-01-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0019_auto_20210109_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='files',
        ),
        migrations.AddField(
            model_name='entryfile',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webgui.entry'),
        ),
        migrations.AddField(
            model_name='entryfile',
            name='team_name',
            field=models.CharField(default='Example Team', max_length=200),
        ),
    ]
