# Generated by Django 3.1.4 on 2021-01-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0020_auto_20210109_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryfile',
            name='team_name',
        ),
    ]
