# Generated by Django 3.1.4 on 2021-01-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0021_remove_entryfile_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfile',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='webgui.entry'),
        ),
    ]
