# Generated by Django 3.1.4 on 2021-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0023_server_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
