# Generated by Django 3.1.4 on 2021-01-10 09:43

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0024_server_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='build_path',
        ),
        migrations.RemoveField(
            model_name='server',
            name='packs_path',
        ),
        migrations.AlterField(
            model_name='entryfile',
            name='file',
            field=models.FileField(upload_to=webgui.util.livery_filename),
        ),
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Change config'), ('U', 'Update liveries')], default='', max_length=3),
        ),
    ]
