# Generated by Django 3.1.4 on 2021-01-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0025_auto_20210110_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Change config'), ('U', 'Update liveries and redeploy')], default='', max_length=3),
        ),
    ]
