# Generated by Django 3.1.4 on 2021-01-10 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0026_auto_20210110_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_version',
            field=models.CharField(default='1.0', help_text="The version to use. You can use 'latest' or 'latest-even' to either get the latest or the latest even version.", max_length=20),
        ),
        migrations.AlterField(
            model_name='component',
            name='do_update',
            field=models.BooleanField(default=False, help_text='If you plan to add liveries on a car, check this.'),
        ),
        migrations.AlterField(
            model_name='component',
            name='short_name',
            field=models.CharField(default='', help_text="The short name is required to idenitfy (livery) filenames belonging to this component. You only need this when 'Do update' is checked.", max_length=200),
        ),
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Update config and redeploy')], default='', help_text='Runs an activity on the server.', max_length=3),
        ),
        migrations.AlterField(
            model_name='server',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event to deploy. Note: You can only change this if the server is not running.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webgui.event'),
        ),
        migrations.AlterField(
            model_name='server',
            name='locked',
            field=models.BooleanField(default=False, help_text='Shows if the server is currently processed by the background worker. During processing, you cannot change settings.'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, default='', help_text='A organistory name for the server', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_ip',
            field=models.CharField(default='', help_text="Not used currently. Use '0.0.0.0' if unkown.", max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='secret',
            field=models.CharField(default='', help_text='The secret for the communication with the APX reciever', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.TextField(blank=True, default=None, help_text='Shows the reported status of the server. Can be empty or a JSON blob.', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='url',
            field=models.CharField(default='', help_text='The URL to the APX reciever', max_length=500),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default=None, help_text="Submits a message or a command to the given server. Can't be longer than 50 chars", max_length=50, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webgui.server')),
            ],
        ),
    ]
