# Generated by Django 3.1.4 on 2021-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0027_auto_20210110_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
