# Generated by Django 3.1.4 on 2021-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0029_chat_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceconditions',
            options={'verbose_name_plural': 'Race conditions'},
        ),
        migrations.AddField(
            model_name='server',
            name='server_key',
            field=models.FileField(blank=True, default=None, help_text='Keyfile of the server', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='server',
            name='server_unlock_key',
            field=models.FileField(blank=True, default=None, help_text='Unlock keyfile of the server', null=True, upload_to=''),
        ),
    ]
