# Generated by Django 3.1.4 on 2021-01-15 18:25

from django.db import migrations, models
import django.db.models.deletion
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0030_auto_20210115_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='locked',
            field=models.BooleanField(default=False, help_text='Shows if the server is currently processed by the background worker. During processing, you cannot change settings.', verbose_name='Processing'),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_key',
            field=models.FileField(blank=True, default=None, help_text='Keyfile of the server. Will be filled automatically.', null=True, upload_to=webgui.util.get_key_root_path),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_unlock_key',
            field=models.FileField(blank=True, default=None, help_text='Unlock keyfile of the server, usually named ServerUnlock.bin, required to use paid content. The field will clear after unlocking', null=True, upload_to=webgui.util.get_key_root_path),
        ),
        migrations.CreateModel(
            name='ServerStatustext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, default=None, help_text='Shows the reported status of the server. Can be empty or a JSON blob.', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webgui.server')),
            ],
        ),
    ]
