# Generated by Django 3.1.4 on 2021-01-16 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgui', '0031_auto_20210115_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverstatustext',
            options={'verbose_name_plural': 'Status history'},
        ),
        migrations.AddField(
            model_name='component',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
