# Generated by Django 3.1.4 on 2021-01-20 19:46

import django.core.validators
from django.db import migrations, models
import webgui.storage
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0033_auto_20210116_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='component',
            name='update',
            field=models.FileField(blank=True, null=True, storage=webgui.storage.OverwriteStorage, upload_to=webgui.util.get_update_filename),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_name',
            field=models.CharField(default='Example_Mod', max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters and dashes are allowed.')]),
        ),
        migrations.AlterField(
            model_name='component',
            name='short_name',
            field=models.CharField(default='', help_text="The short name is required to idenitfy (livery) filenames belonging to this component. You only need this when 'Do update' is checked.", max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters and dashes are allowed.')]),
        ),
        migrations.AlterField(
            model_name='entryfile',
            name='file',
            field=models.FileField(storage=webgui.storage.OverwriteStorage, upload_to=webgui.util.livery_filename),
        ),
        migrations.AlterField(
            model_name='raceconditions',
            name='rfm',
            field=models.FileField(storage=webgui.storage.OverwriteStorage, upload_to=webgui.util.get_conditions_file_root),
        ),
    ]
