# Generated by Django 3.1.4 on 2021-01-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0034_auto_20210120_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status_failures',
            field=models.IntegerField(default=0, help_text='The amount of failed status checks'),
        ),
    ]
