# Generated by Django 3.1.4 on 2021-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0035_server_status_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='template',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='status_failures',
            field=models.IntegerField(default=0, help_text='The amount of failed status checks. The field will reset on save. If more than 3 attemps will fail, the server will be ignored for status and actions..'),
        ),
    ]
