# Generated by Django 3.1.4 on 2021-02-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0037_auto_20210206_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
