# Generated by Django 3.1.4 on 2021-02-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0038_entry_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
