# Generated by Django 3.1.4 on 2021-02-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0039_auto_20210207_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfile',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webgui.entry'),
        ),
    ]
