# Generated by Django 3.1.4 on 2021-02-10 17:55

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0040_auto_20210207_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='log',
            field=models.FileField(blank=True, default=None, help_text='The logfile of the server for troublsehooting purposes', null=True, upload_to=webgui.util.get_logfile_root_path),
        ),
    ]
