# Generated by Django 3.1.4 on 2021-02-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0041_server_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='steam_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
