# Generated by Django 3.1.4 on 2021-02-12 19:13

from django.db import migrations, models
import webgui.storage
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0042_auto_20210212_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfile',
            name='file',
            field=models.FileField(max_length=500, storage=webgui.storage.OverwriteStorage, upload_to=webgui.util.livery_filename),
        ),
    ]
