# Generated by Django 3.1.4 on 2021-02-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgui', '0043_auto_20210212_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Add description')),
                ('date_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Race sessions',
            },
        ),
        migrations.AddField(
            model_name='raceconditions',
            name='sessions',
            field=models.ManyToManyField(to='webgui.RaceSessions'),
        ),
    ]
