# Generated by Django 3.1.4 on 2021-02-14 11:04

from django.db import migrations, models
import webgui.storage
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0045_auto_20210214_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesessions',
            name='grip',
            field=models.FileField(blank=True, default=None, null=True, storage=webgui.storage.OverwriteStorage, upload_to=webgui.util.get_conditions_file_root),
        ),
    ]
