# Generated by Django 3.1.4 on 2021-02-14 11:28

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0046_racesessions_grip'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='settingsPath',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='weatherFileName',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='racesessions',
            name='grip',
            field=models.FileField(blank=True, default=None, null=True, upload_to=webgui.util.get_conditions_file_root),
        ),
    ]
