# Generated by Django 3.1.4 on 2021-02-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0047_auto_20210214_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='settingsPath',
            new_name='settings_path',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='weatherFileName',
            new_name='weather_file_name',
        ),
    ]
