# Generated by Django 3.1.4 on 2021-02-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0048_auto_20210214_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='settings_path',
        ),
        migrations.RemoveField(
            model_name='track',
            name='weather_file_name',
        ),
    ]
