# Generated by Django 3.1.4 on 2021-02-14 12:30

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0049_auto_20210214_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racesessions',
            name='grip',
            field=models.FileField(default='foo', upload_to=webgui.util.get_conditions_file_root),
            preserve_default=False,
        ),
    ]
