# Generated by Django 3.1.4 on 2021-02-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0050_auto_20210214_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceconditions',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='webgui.RaceSessions'),
        ),
    ]
