# Generated by Django 3.1.4 on 2021-02-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0051_auto_20210214_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesessions',
            name='laps',
            field=models.IntegerField(default=0, help_text='Target laps of the session'),
        ),
        migrations.AddField(
            model_name='racesessions',
            name='length',
            field=models.IntegerField(default=0, help_text='Target length of the session in minutes'),
        ),
        migrations.AddField(
            model_name='racesessions',
            name='start',
            field=models.TimeField(blank=True, default=None, help_text='Target laps fro this session', null=True),
        ),
    ]
