# Generated by Django 3.1.4 on 2021-02-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0052_auto_20210217_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_type',
            field=models.CharField(choices=[('S', 'Standing start'), ('FLS', 'Formation Lap and standing start'), ('SCR', 'Lap behind safety car & rolling start'), ('FR', 'Fast rolling start')], default='S', max_length=3),
        ),
        migrations.AlterField(
            model_name='racesessions',
            name='start',
            field=models.TimeField(blank=True, default=None, help_text='Target laps fro this session. This is in-game time. If empty, the defaults will be used.', null=True),
        ),
        migrations.AlterField(
            model_name='racesessions',
            name='type',
            field=models.CharField(choices=[('TD', 'Training Day'), ('P1', 'Practice 1'), ('Q1', 'Qualy 1'), ('WU', 'Warmup'), ('R1', 'Race 1')], default='TD', max_length=2),
        ),
    ]
