# Generated by Django 3.1.4 on 2021-02-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0053_auto_20210219_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='branch',
            field=models.CharField(choices=[('RC', 'release-candidate'), ('P', 'public')], default='P', help_text='Public steam branch', max_length=4),
        ),
    ]
