# Generated by Django 3.1.4 on 2021-02-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0054_server_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='branch',
            field=models.CharField(choices=[('release-candidate', 'release-candidate'), ('public', 'public')], default='public', help_text='Public steam branch', max_length=50),
        ),
    ]
