# Generated by Django 3.1.4 on 2021-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0055_auto_20210220_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='real_weather',
            field=models.BooleanField(default=False, help_text='Decides if real weather should be used. The weather is based on a hourly forecast.'),
        ),
    ]
