# Generated by Django 3.1.4 on 2021-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0056_event_real_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='temp_offset',
            field=models.IntegerField(default=0, help_text='Adds a positive or negative number to the temperature in Celsius.'),
        ),
    ]
