# Generated by Django 3.1.4 on 2021-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0057_event_temp_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='vehicle_number',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
