# Generated by Django 3.1.4 on 2021-02-27 17:51

from django.db import migrations, models
import webgui.storage
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ("webgui", "0058_auto_20210227_1817"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="livery_mask",
            field=models.FileField(
                blank=True,
                null=True,
                storage=webgui.storage.OverwriteStorage,
                upload_to=webgui.util.get_livery_mask_root,
            ),
        ),
    ]
