# Generated by Django 3.1.4 on 2021-02-27 18:13

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0059_component_livery_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryfile',
            name='mask_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='livery_mask',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=webgui.util.get_livery_mask_root),
        ),
    ]
