# Generated by Django 3.1.4 on 2021-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0060_auto_20210227_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='mask_positions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
