# Generated by Django 3.1.4 on 2021-02-28 09:31

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0062_auto_20210227_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='numberplate_template_mask',
            field=models.FileField(blank=True, help_text='A dds file containing the region information for the numberplate. Will be added on top of a given _Region.dds file.', max_length=255, null=True, upload_to=webgui.util.get_livery_mask_root),
        ),
        migrations.AlterField(
            model_name='component',
            name='numberplate_template',
            field=models.FileField(blank=True, help_text='A dds file containing the numberplate background. Numbers will be applied.', max_length=255, null=True, upload_to=webgui.util.get_livery_mask_root),
        ),
    ]
