# Generated by Django 3.1.4 on 2021-02-28 10:31

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0063_auto_20210228_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='numberplate_template',
        ),
        migrations.RemoveField(
            model_name='component',
            name='numberplate_template_mask',
        ),
        migrations.AddField(
            model_name='component',
            name='numberplate_template_l',
            field=models.FileField(blank=True, help_text='A dds file containing the left numberplate background. Numbers will be applied.', max_length=255, null=True, upload_to=webgui.util.get_livery_mask_root),
        ),
        migrations.AddField(
            model_name='component',
            name='numberplate_template_mask_l',
            field=models.FileField(blank=True, help_text='A dds file containing the region information for the left numberplate. Will be added on top of a given _Region.dds file.', max_length=255, null=True, upload_to=webgui.util.get_livery_mask_root),
        ),
        migrations.AddField(
            model_name='component',
            name='numberplate_template_mask_r',
            field=models.FileField(blank=True, help_text='A dds file containing the region information for the leftright numberplate. Will be added on top of a given _Region.dds file.', max_length=255, null=True, upload_to=webgui.util.get_livery_mask_root),
        ),
        migrations.AddField(
            model_name='component',
            name='numberplate_template_r',
            field=models.FileField(blank=True, help_text='A dds file containing the right numberplate background. Numbers will be applied.', max_length=255, null=True, upload_to=webgui.util.get_livery_mask_root),
        ),
    ]
