# Generated by Django 3.1.4 on 2021-03-07 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0065_server_public_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mod_name',
            field=models.CharField(default='', help_text='Name of the mod to install. If no value is given, the scheme apx_{randomstring} will be used. Max length is 50 chars.', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters and dashes are allowed.')]),
        ),
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Update config and redeploy')], default='', help_text='Runs an activity on the server.', max_length=3, verbose_name='Pending action to submit'),
        ),
        migrations.AlterField(
            model_name='server',
            name='locked',
            field=models.BooleanField(default=False, help_text='Shows if the server is currently processed by the background worker. During processing, you cannot change settings.', verbose_name='Processing pending action'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='hdfgifcicebbgaigiaca', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
