# Generated by Django 3.1.4 on 2021-03-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0067_auto_20210307_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='adcfabacfeehdfbbfebf', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
