# Generated by Django 3.1.4 on 2021-03-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0069_auto_20210320_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='signup_components',
            field=models.ManyToManyField(to='webgui.Component'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='chbiccfibahcbdeebehe', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
