# Generated by Django 3.1.4 on 2021-03-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0070_auto_20210320_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Update config and redeploy'), ('W', 'Restart weekend')], default='', help_text='Runs an activity on the server.', max_length=3, verbose_name='Pending action to submit'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='feddaiaafgebedagdhih', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
