# Generated by Django 3.1.4 on 2021-03-20 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webgui.storage
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgui', '0071_auto_20210320_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gicdcghieiiehbbeggab', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.CreateModel(
            name='ComponentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, storage=webgui.storage.OverwriteStorage, upload_to=webgui.util.get_component_file_root)),
                ('type', models.CharField(choices=[('window', 'Window skin (GT3)'), ('windows', 'Window skin'), ('windowsin', 'Windows (inside)'), ('windowsout', 'Windows (outside)')], default='window', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
