# Generated by Django 3.1.4 on 2021-03-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0072_auto_20210320_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='files',
            field=models.ManyToManyField(to='webgui.ComponentFile'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ahdhiebeffihiegchbec', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
