# Generated by Django 3.1.4 on 2021-03-28 07:14

from django.db import migrations, models
import django.db.models.deletion
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0073_auto_20210320_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentfile',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webgui.component'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='files',
            field=models.ManyToManyField(related_name='component_file_list', to='webgui.ComponentFile'),
        ),
        migrations.AlterField(
            model_name='componentfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=webgui.util.get_component_file_root),
        ),
        migrations.AlterField(
            model_name='componentfile',
            name='type',
            field=models.CharField(choices=[('window.dds', 'Window skin (GT3)'), ('windows.dds', 'Window skin'), ('windowsin.dds', 'Windows (inside)'), ('windowsout.dds', 'Windows (outside)')], default='window.dds', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='afgibfcdigedeidgdeei', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
