# Generated by Django 3.1.4 on 2021-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0076_auto_20210328_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='files',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ciddfbicfddebihhehch', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
