# Generated by Django 3.1.4 on 2021-04-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0078_auto_20210328_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gaghdehadffiedfgibid', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.CreateModel(
            name='ServerCron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_text', models.CharField(default=None, max_length=255)),
                ('action', models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Update config and redeploy'), ('W', 'Restart weekend')], default='', help_text='Runs an activity on the server.', max_length=3, verbose_name='Pending action to submit')),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webgui.event')),
                ('server', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webgui.server')),
            ],
        ),
    ]
