# Generated by Django 3.1.4 on 2021-04-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0080_auto_20210405_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercron',
            name='last_execution',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='cfaiehbbidcbgghdaicc', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
