# Generated by Django 3.1.4 on 2021-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0081_auto_20210405_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercron',
            name='pending_for_execution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='eehcfchagchgfgibgdcf', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
