# Generated by Django 3.1.4 on 2021-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0082_auto_20210405_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servercron',
            name='pending_for_execution',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='fhdibaigdbhggcbbbfae', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
