# Generated by Django 3.1.4 on 2021-04-08 15:13

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0083_auto_20210405_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servercron',
            options={'verbose_name': 'Server schedule', 'verbose_name_plural': 'Server schedules'},
        ),
        migrations.AlterField(
            model_name='racesessions',
            name='grip',
            field=models.FileField(blank=True, default=None, null=True, upload_to=webgui.util.get_conditions_file_root),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gdbiiaabfffifeaafbeb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='servercron',
            name='cron_text',
            field=models.CharField(default=None, help_text='Describe the execution time', max_length=255),
        ),
    ]
