# Generated by Django 3.1.4 on 2021-04-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0084_auto_20210408_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status_websocket',
            field=models.CharField(default='', help_text='The status websocket of the server', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='entries',
            field=models.ManyToManyField(blank=True, to='webgui.Entry'),
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_components',
            field=models.ManyToManyField(help_text='Components allowed to be registered. If no entries are existing, all available entries from the mod will be used.', to='webgui.Component'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bcdcfaiafihgdfcdccih', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
