# Generated by Django 3.1.4 on 2021-04-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0085_auto_20210410_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ieacddhbffhbbgiaiiag', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='status_websocket',
            field=models.CharField(blank=True, default=None, help_text='The status websocket of the server', max_length=500, null=True),
        ),
    ]
