# Generated by Django 3.1.4 on 2021-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0086_auto_20210410_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='status_websocket',
        ),
        migrations.AddField(
            model_name='entry',
            name='additional_overwrites',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Additional overwrites. See https://wiki.apx.chmr.eu/doku.php?id=wizard_additional_overwrites for details.'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gcfhccaebdbhhdcfbide', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
