# Generated by Django 3.1.4 on 2021-04-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0087_auto_20210410_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gfhebfeibggieaaifcdd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
