# Generated by Django 3.1.4 on 2021-04-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0088_auto_20210410_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='additional_overwrites',
            field=models.TextField(blank=True, default=None, null=True, verbose_name="See Wiki article 'Wizard: Additional properties for entries' for details"),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='haacighcigibafiieffd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.CreateModel(
            name='TickerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(default=None, help_text='Event description', max_length=255)),
                ('type', models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Update config and redeploy'), ('W', 'Restart weekend')], default='', help_text='Runs an activity on the server.', max_length=3, verbose_name='Pending action to submit')),
                ('affected_vehicles', models.ManyToManyField(blank=True, to='webgui.Entry')),
                ('server', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webgui.server')),
            ],
            options={
                'verbose_name_plural': 'Ticker messages',
            },
        ),
    ]
