# Generated by Django 3.1.4 on 2021-04-12 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgui', '0089_auto_20210412_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickermessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='dehffbhiaigdbfcgideb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
