# Generated by Django 3.1.4 on 2021-04-17 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgui', '0090_auto_20210412_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='dhffgebifgefgedfbiih', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='tickermessage',
            name='type',
            field=models.CharField(blank=True, choices=[('P+', 'Penalty')], default='', help_text='Type', max_length=3, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ServerPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_unlock_key', models.FileField(default=None, help_text='The plugin file', upload_to=webgui.util.get_plugin_root_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
