# Generated by Django 3.1.4 on 2021-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0092_auto_20210417_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverplugin',
            old_name='server_unlock_key',
            new_name='plugin_file',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ggbhabcdafaecgcddbid', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
