# Generated by Django 3.1.4 on 2021-04-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0093_auto_20210417_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverplugin',
            name='name',
            field=models.CharField(blank=True, default='', help_text='A organistory name for the plugin', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serverplugin',
            name='overwrites',
            field=models.TextField(default='{}', help_text='Additional JSON settings to use'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ibciaedggagchfegfbbb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
