# Generated by Django 3.1.4 on 2021-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0094_auto_20210417_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='plugins',
            field=models.ManyToManyField(blank=True, to='webgui.ServerPlugin'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='acgbceiifehgdfcbhhgf', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='serverplugin',
            name='overwrites',
            field=models.TextField(default='{}', help_text="Additional JSON settings to use. ' Enabled: 1' will be added automatically."),
        ),
    ]
