# Generated by Django 3.1.4 on 2021-05-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0096_auto_20210417_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='update_on_build',
            field=models.BooleanField(default=False, help_text='Decides if APX will call dedicated server update when refreshing the content'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bbgfdcahifghffbidfei', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='status_failures',
            field=models.IntegerField(default=0, help_text='The amount of failed status checks. The field will reset on save. If more than 500 attemps will fail, the server will be ignored for status and actions..'),
        ),
    ]
