# Generated by Django 3.1.4 on 2021-05-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0097_auto_20210508_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bdheighheeggabiaaaah', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
