# Generated by Django 3.1.4 on 2021-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0098_auto_20210508_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickermessage',
            name='affected_vehicles',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_ip',
            field=models.CharField(default='0.0.0.0', help_text="Not used currently. Use '0.0.0.0' if unkown.", max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ebbedihibieafdcgabah', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='tickermessage',
            name='type',
            field=models.CharField(blank=True, choices=[('P+', 'PenaltyAdd'), ('P-', 'Penaltyrevoke'), ('V', 'SlowCar'), ('PI', 'PitEntry'), ('PO', 'PitExit'), ('S', 'StatusChange'), ('P', 'PositionChange')], default='', help_text='Type', max_length=3, verbose_name='Type'),
        ),
    ]
