# Generated by Django 3.1.4 on 2021-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0099_auto_20210521_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickermessage',
            name='event_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='hhaidbhhgcddgehceebc', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='tickermessage',
            name='type',
            field=models.CharField(blank=True, choices=[('P+', 'PenaltyAdd'), ('P-', 'Penaltyrevoke'), ('V', 'SlowCar'), ('PI', 'PitEntry'), ('PO', 'PitExit'), ('GI', 'GarageEntry'), ('GO', 'GarageExit'), ('S', 'StatusChange'), ('P', 'PositionChange'), ('PY', 'PositionChangeUnderYellow'), ('PB', 'BestLapChange'), ('PS', 'PitStatusChange'), ('L', 'Lag'), ('LC', 'LapsCompletedChange'), ('PSS', 'PittingStart'), ('PSE', 'PittingEnd')], default='', help_text='Type', max_length=3, verbose_name='Type'),
        ),
    ]
