# Generated by Django 3.1.4 on 2021-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0102_auto_20210522_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickermessage',
            name='session',
            field=models.CharField(blank=True, default=None, help_text='In game session identifier', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='defigiafgdabgchgdbcg', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
