# Generated by Django 3.1.4 on 2021-05-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0103_auto_20210522_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timing_classes',
            field=models.TextField(blank=True, default='{}', help_text='JSON Config to rename classes, if needed'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ebebcdiagibfhcgbcidc', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='tickermessage',
            name='type',
            field=models.CharField(blank=True, choices=[('P+', 'PenaltyAdd'), ('P-', 'Penaltyrevoke'), ('V', 'SlowCar'), ('PI', 'PitEntry'), ('PO', 'PitExit'), ('GI', 'GarageEntry'), ('GO', 'GarageExit'), ('S', 'StatusChange'), ('P', 'PositionChange'), ('PY', 'PositionChangeUnderYellow'), ('PB', 'BestLapChange'), ('PS', 'PitStatusChange'), ('L', 'Lag'), ('LC', 'LapsCompletedChange'), ('PSS', 'PittingStart'), ('PSE', 'PittingEnd'), ('DS', 'DriverSwap')], default='', help_text='Type', max_length=3, verbose_name='Type'),
        ),
    ]
