# Generated by Django 3.1.4 on 2021-06-03 09:34

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0104_auto_20210530_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='log',
        ),
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='aeahgcgdefadcecfabbf', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_key',
            field=models.FileField(blank=True, default=None, help_text='Keyfile of the server. Will be filled on save', null=True, upload_to=webgui.util.get_key_root_path),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_unlock_key',
            field=models.FileField(blank=True, default=None, help_text='Unlock keyfile of the server, usually named ServerUnlock.bin, required to use paid content. The field will cleared after unlocking', null=True, upload_to=webgui.util.get_key_root_path),
        ),
    ]
