# Generated by Django 3.1.4 on 2021-06-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0106_auto_20210605_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesessions',
            name='weather',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='cabcgcafhfcfhegedeid', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
