# Generated by Django 3.1.4 on 2021-06-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0107_auto_20210605_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Latitute'),
        ),
        migrations.AddField(
            model_name='track',
            name='lon',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Longitute'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='hdbbighhbceacgfdgggh', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
