# Generated by Django 3.1.4 on 2021-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0109_auto_20210605_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='update_weather_on_start',
            field=models.BooleanField(default=False, help_text='Decides if APX will update the weather data on start if real weather is enabled'),
        ),
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Update config and redeploy'), ('W', 'Restart weekend'), ('WU', 'Weather forecast update')], default='', help_text='Runs an activity on the server.', max_length=3, verbose_name='Pending action to submit'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gghdfabdchdiieifddgi', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='servercron',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Update config and redeploy'), ('W', 'Restart weekend'), ('WU', 'Weather forecast update')], default='', help_text='Runs an activity on the server.', max_length=3, verbose_name='Pending action to submit'),
        ),
    ]
