# Generated by Django 3.1.4 on 2021-06-13 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webgui.storage
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgui', '0110_auto_20210605_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, storage=webgui.storage.OverwriteStorage, upload_to=webgui.util.livery_filename)),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ehgabhbdgiagfacgdfec', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.CreateModel(
            name='TrackUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webgui.component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
