# Generated by Django 3.1.4 on 2021-06-13 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgui', '0112_auto_20210613_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfile',
            name='Track',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webgui.trackupdate'),
        ),
        migrations.AddField(
            model_name='trackfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='beiieebecbgageiacebe', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
