# Generated by Django 3.1.4 on 2021-06-13 09:46

from django.db import migrations, models
import webgui.storage
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0113_auto_20210613_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackfile',
            old_name='Track',
            new_name='track',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bagcfbbdhhdcfhgiahha', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='trackfile',
            name='file',
            field=models.FileField(max_length=500, storage=webgui.storage.OverwriteStorage, upload_to=webgui.util.track_filename),
        ),
    ]
