# Generated by Django 3.1.4 on 2021-06-13 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0115_auto_20210613_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mod_version',
            field=models.CharField(blank=True, default='', help_text="Version suffix to be used. If not set, the value '.9apx' will be used.", max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.]*$', 'Only alphanumeric characters and dots are allowed.')]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='caegbcdchadcgdaeabbb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
