# Generated by Django 3.1.4 on 2021-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0116_auto_20210613_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='section_list',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Track sections'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='hadhfhcecbbdfaedbidb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='tickermessage',
            name='type',
            field=models.CharField(blank=True, choices=[('P+', 'PenaltyAdd'), ('P-', 'Penaltyrevoke'), ('V', 'SlowCar'), ('PI', 'PitEntry'), ('PO', 'PitExit'), ('GI', 'GarageEntry'), ('GO', 'GarageExit'), ('S', 'StatusChange'), ('P', 'PositionChange'), ('PY', 'PositionChangeUnderYellow'), ('PB', 'BestLapChange'), ('PS', 'PitStatusChange'), ('L', 'Lag'), ('LC', 'LapsCompletedChange'), ('PSS', 'PittingStart'), ('PSE', 'PittingEnd'), ('DS', 'DriverSwap'), ('VL', 'VLow')], default='', help_text='Type', max_length=3, verbose_name='Type'),
        ),
    ]
