# Generated by Django 3.1.4 on 2021-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0118_auto_20210724_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='eedghfcgghdhcaiheicb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.DeleteModel(
            name='ServerStatustext',
        ),
    ]
