# Generated by Django 3.1.4 on 2021-07-24 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0121_auto_20210724_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_mod_version',
            field=models.CharField(blank=True, default='', help_text="Version suffix to be used for the mod itself. If not set, a RANDOM value in concatenation with '1.0+{random}' will be used.", max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.]*$', 'Only alphanumeric characters and dots are allowed.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='mod_version',
            field=models.CharField(blank=True, default=None, help_text="Version suffix to be used for content updates (track, cars). If not set, the value '.9apx' will be used.", max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.]*$', 'Only alphanumeric characters and dots are allowed.')]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='dgfbdcgfhbfdidcdbfbb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
