# Generated by Django 3.1.4 on 2021-07-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0122_auto_20210724_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='component',
            name='user',
        ),
        migrations.RemoveField(
            model_name='componentfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entryfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='raceconditions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='racesessions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='server',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servercron',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serverplugin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tickermessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trackfile',
            name='user',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='icacdafifhhcahaegbbd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
