# Generated by Django 3.1.4 on 2021-07-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0123_auto_20210724_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='state',
            field=models.TextField(blank=True, default=None, help_text='The last update info got from the reciever', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gebbceaibbecbafhefdg', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
