# Generated by Django 3.1.4 on 2021-07-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0124_auto_20210725_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='locked',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='hcadihffdcfaggbiiedb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
