# Generated by Django 3.1.4 on 2021-07-28 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0125_auto_20210725_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_password',
            field=models.CharField(default='apx', help_text='Admin password. Has max length of 50 chars. Cannot be empty', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='damage',
            field=models.IntegerField(default=10, help_text='Damage multiplier', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(109)]),
        ),
        migrations.AddField(
            model_name='event',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Join password. Has max length of 50 chars.', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ciafieiebcciibcbacfc', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
