# Generated by Django 3.1.4 on 2021-07-28 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0126_auto_20210728_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejoin',
            field=models.CharField(choices=[('0', 'No rejoin'), ('1', 'yes with fresh vehicle'), ('2', 'yes with vehicle in same physical condition'), ('3', 'yes including setup')], default='0', help_text='Race rejoin ruling', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='damage',
            field=models.IntegerField(default=100, help_text='Damage multiplier', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bhifcfgcadeihhhfiafd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
