# Generated by Django 3.1.4 on 2021-07-28 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0127_auto_20210728_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_clients',
            field=models.IntegerField(default=0, help_text='Allowed AI clients', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(109)]),
        ),
        migrations.AddField(
            model_name='event',
            name='clients',
            field=models.IntegerField(default=20, help_text='Allowed clients', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(109)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gabbagcciegdehgieecg', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
