# Generated by Django 3.1.4 on 2021-07-28 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0128_auto_20210728_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='downstream',
            field=models.IntegerField(default=0, help_text='Downstream in KBPS. Calculate with 2000 per client.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AddField(
            model_name='event',
            name='real_name',
            field=models.BooleanField(default=False, help_text='Decides if the server forces the client to expose the real name'),
        ),
        migrations.AddField(
            model_name='event',
            name='upstream',
            field=models.IntegerField(default=0, help_text='Upstream in KBPS. Calculate with 2000 per client.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gihihgfdhccfbdbgbhgc', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
