# Generated by Django 3.1.4 on 2021-07-28 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0129_auto_20210728_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='replays',
            field=models.BooleanField(default=False, help_text='Enable or disable replays for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='webui_port',
            field=models.IntegerField(default=1025, help_text='Port for the webui_port. Must be unique on all managed servers', validators=[django.core.validators.MinValueValidator(1025), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='diidibigfhidgdiedhic', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
