# Generated by Django 3.1.4 on 2021-07-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0130_auto_20210728_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='overwrites_multiplayer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='overwrites_player',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='edbfeidhicdihfbffecd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
