# Generated by Django 3.1.4 on 2021-07-28 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0131_auto_20210728_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_ai_toggle',
            field=models.BooleanField(default=False, help_text='Allow AI toggle'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_auto_clutch',
            field=models.BooleanField(default=True, help_text='Allow auto clutch'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_auto_pit_stop',
            field=models.BooleanField(default=False, help_text='Allow auto pit stop'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_auto_shifting',
            field=models.IntegerField(default=2, help_text='Allow Stability Control', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_invulnerability',
            field=models.BooleanField(default=False, help_text='Allow Invulnerability'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_opposite_lock',
            field=models.BooleanField(default=False, help_text='Allow opposite lock'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_spin_recovery',
            field=models.BooleanField(default=False, help_text='Allow spin recovery'),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_stability_control',
            field=models.IntegerField(default=2, help_text='Allow Stability Control', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_steering_help',
            field=models.IntegerField(default=2, help_text='Allow braking help', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_traction_control',
            field=models.IntegerField(default=2, help_text='Allow Anti-Lock Braking', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bhahcbfcbdffeedebihb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
