# Generated by Django 3.1.4 on 2021-07-28 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0132_auto_20210728_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_anti_lock_brakes',
            field=models.IntegerField(default=2, help_text='Allow Anti-Lock Braking', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_braking_help',
            field=models.IntegerField(default=2, help_text='Allow braking help', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_steering_help',
            field=models.IntegerField(default=2, help_text='Allow steering help', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_traction_control',
            field=models.IntegerField(default=3, help_text='Allow traction control', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='hhaaecdgffecfieieaff', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
