# Generated by Django 3.1.4 on 2021-07-28 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0135_auto_20210728_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fuel_multiplier',
            field=models.IntegerField(default=1, help_text='Fuel usage multiplier, use 0 to disable completely', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='tire_multiplier',
            field=models.IntegerField(default=1, help_text='Tire usage multiplier, use 0 to disable completely', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bgceahecccdgaafbghfc', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
