# Generated by Django 3.1.4 on 2021-07-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0136_auto_20210728_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='race_multiplier',
            field=models.CharField(choices=[('-1', 'Race %'), ('0', 'None'), ('1', 'Normal'), ('2', 'x2'), ('3', 'x3'), ('4', 'x4'), ('5', 'x5'), ('10', 'x10'), ('15', 'x15'), ('20', 'x20'), ('25', 'x25'), ('30', 'x30'), ('45', 'x45'), ('60', 'x60')], default='1', help_text='Race time scale', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='cieabagiedhcefggchcd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
