# Generated by Django 3.1.4 on 2021-07-28 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0137_auto_20210728_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='http_port',
            field=models.IntegerField(default=64297, help_text='Port for the HTTP Server. Must be unique on all managed servers', validators=[django.core.validators.MinValueValidator(1025), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='event',
            name='sim_port',
            field=models.IntegerField(default=54297, help_text='Port for the Simulation. Must be unique on all managed servers', validators=[django.core.validators.MinValueValidator(1025), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_name',
            field=models.CharField(default='Example_Mod', max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters and dashes are allowed.')]),
        ),
        migrations.AlterField(
            model_name='component',
            name='short_name',
            field=models.CharField(default='', help_text="The short name is required to idenitfy (livery) filenames belonging to this component. You only need this when 'Do update' is checked.", max_length=200, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters and dashes are allowed.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='mod_name',
            field=models.CharField(blank=True, default='', help_text='Name of the mod to install. If no value is given, the scheme apx_{randomstring} will be used. Max length is 50 chars.', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters and dashes are allowed.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='race_multiplier',
            field=models.CharField(choices=[('-1', 'Race %'), ('0', 'None'), ('1', 'Normal'), ('2', 'x2'), ('3', 'x3'), ('4', 'x4'), ('5', 'x5'), ('10', 'x10'), ('15', 'x15'), ('20', 'x20'), ('25', 'x25'), ('30', 'x30'), ('45', 'x45'), ('60', 'x60')], default='1', help_text='Race time scale', max_length=50, verbose_name='Race time scale'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='afgbgbgdchdedeifffgh', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
