# Generated by Django 3.1.4 on 2021-07-29 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0138_auto_20210728_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='http_port',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sim_port',
        ),
        migrations.RemoveField(
            model_name='event',
            name='webui_port',
        ),
        migrations.AddField(
            model_name='server',
            name='http_port',
            field=models.IntegerField(default=64297, help_text='Port for the HTTP Server. Must be unique on all managed servers', validators=[django.core.validators.MinValueValidator(1025), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='server',
            name='sim_port',
            field=models.IntegerField(default=54297, help_text='Port for the Simulation. Must be unique on all managed servers', validators=[django.core.validators.MinValueValidator(1025), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='server',
            name='webui_port',
            field=models.IntegerField(default=1025, help_text='Port for the webui_port. Must be unique on all managed servers', validators=[django.core.validators.MinValueValidator(1025), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='dgdiiccagigidageadbb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
