# Generated by Django 3.1.4 on 2021-07-31 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0139_auto_20210729_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_mod_version',
            field=models.CharField(blank=True, default='', help_text="Version suffix to be used for the mod itself. If not set, a RANDOM value in concatenation with '1.0+{random}' will be used.", max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.\\%]*$', 'Only alphanumeric characters and dots are allowed.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='mod_version',
            field=models.CharField(blank=True, default=None, help_text="Version suffix to be used for content updates (track, cars). If not set, the value '.9apx' will be used.", max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z.\\%]*$', 'Only alphanumeric characters and dots are allowed.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='branch',
            field=models.CharField(choices=[('release-candidate', 'release-candidate'), ('public', 'public'), ('previous-release', 'previous-release'), ('v1121', 'v1121'), ('v1122', 'v1122'), ('old-ui', 'old-ui')], default='public', help_text='Public steam branch', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='aiciggffefbgfghgaief', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
