# Generated by Django 3.1.4 on 2021-08-01 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0140_auto_20210731_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='steamcmd_bandwith',
            field=models.IntegerField(default=0, help_text='Limit the bandwith steamcmd may use. 0 means unlimited download. Value is kbit/s. Maximum is 1000000', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bbfabbbabfffdchghecb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
