# Generated by Django 3.1.4 on 2021-08-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0142_auto_20210802_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='collect_results_replays',
            field=models.BooleanField(default=False, help_text='Decides if APX will allow the server to persist the result and replay files'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='chhiageibgdcfabeghai', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
