# Generated by Django 3.1.4 on 2021-08-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0143_auto_20210802_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_official',
            field=models.BooleanField(default=False, help_text='Is official content (important for selecting base versions)'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='fggiichfgdagcdhcbheb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
