# Generated by Django 3.1.4 on 2021-08-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0145_auto_20210804_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='abfedgdigdicabiegbeb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='trackfile',
            name='track',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webgui.track'),
        ),
    ]
