# Generated by Django 3.1.4 on 2021-08-13 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0147_auto_20210805_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgui.server'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgui.component'),
        ),
        migrations.AlterField(
            model_name='event',
            name='conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgui.raceconditions'),
        ),
        migrations.AlterField(
            model_name='server',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event to deploy. Note: You can only change this if the server is not running.', null=True, on_delete=django.db.models.deletion.CASCADE, to='webgui.event'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bbbbdfgibeeahhbabgcf', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgui.component'),
        ),
    ]
