# Generated by Django 3.1.4 on 2021-08-15 08:07

from django.db import migrations, models
import webgui.models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0148_auto_20210813_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', help_text='The Name of the event. Will be used as Race name in the server.', max_length=26, validators=[webgui.models.event_name_validator]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='dcchcebcbfaccbghffha', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
