# Generated by Django 3.1.4 on 2021-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0149_auto_20210815_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='cadfdgfhihfaibdcebgd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.DeleteModel(
            name='ComponentFile',
        ),
    ]
