# Generated by Django 3.1.4 on 2021-08-30 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0154_auto_20210822_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cuts_allowed',
            field=models.IntegerField(default=2, help_text='Cuts allowed before the game gives out a penalty', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='event',
            name='qualy_mode',
            field=models.CharField(choices=[('0', 'all cars qualify visibly on track together'), ('1', 'only one car is visible at a time'), ('2', 'use default from RFM, season, or track entry')], default='2', help_text='Qualy mode', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='include_stock_skins',
            field=models.BooleanField(default=False, help_text='Attempt to add stock skins even if own liveries are used.'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gbaccchbghdebeggghig', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
