# Generated by Django 3.1.4 on 2021-08-30 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0155_auto_20210830_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blue_flag_mode',
            field=models.CharField(choices=[('0', 'None'), ('1', 'show but never penalize'), ('2', 'show and penalize if following within 0.3 seconds'), ('3', 'show and penalize if following within 0.5 seconds'), ('4', 'show and penalize if following within 0.7 seconds'), ('5', 'show and penalize if following within 0.7 seconds'), ('6', 'show and penalize if following within 1.1 seconds'), ('7', 'Use rFm value')], default='1', help_text='Blue flag mode', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='cuts_allowed',
            field=models.IntegerField(default=2, help_text='Track cuts allowed before a penalty is given', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='biiihbachebbfhbhgigb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
