# Generated by Django 3.1.4 on 2021-08-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0156_auto_20210830_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pause_while_zero_players',
            field=models.BooleanField(default=False, help_text='Pause while zero players'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='faadabgeiieicedighga', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
