# Generated by Django 3.1.4 on 2021-08-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0159_auto_20210831_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qualy_join_mode',
            field=models.CharField(choices=[('0', 'Open to all'), ('1', 'Open but drivers will be pending an open session'), ('2', 'closed')], default='0', help_text='Closed Qualify Sessions', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='cdigegbdddicaaaeaecf', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
