# Generated by Django 3.1.4 on 2021-08-31 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0161_auto_20210831_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='after_race_delay',
            field=models.IntegerField(default=90, help_text='Dedicated server additional delay (added to delay between sessions before loading next track', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='delay_between_sessions',
            field=models.IntegerField(default=30, help_text='Dedicated server delay before switching sessions automatically (after hotlaps are completed, if option is enabled), previously hardcoded to 45', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bdidhiigecigfafciicb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
