# Generated by Django 3.1.4 on 2021-08-31 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0164_auto_20210831_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recoonaissance_laps',
            field=models.IntegerField(default=0, help_text='Reconnaissance laps', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='conditions',
            field=models.ForeignKey(help_text='Conditions is a bundle of session definitions, containing session lengths and grip information.', on_delete=django.db.models.deletion.CASCADE, to='webgui.raceconditions'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='cgbbhicfdcfaddedbbdd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
