# Generated by Django 3.1.4 on 2021-08-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0165_auto_20210831_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='recoonaissance_laps',
            new_name='reconaissance_laps',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='iiggbcahigcbcffcahef', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
