# Generated by Django 3.1.4 on 2021-08-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0166_auto_20210831_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parc_ferme',
            field=models.CharField(choices=[('0', 'Off'), ('1', "no setup changes allowed between qual and race except for 'Free Settings')"), ('2', 'same unless rain'), ('3', 'use RFM default')], default='3', help_text='Parc Ferme ruling. If enforced, add values for the Free Settings field aswell', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ebahchegcihaecfegefh', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
