# Generated by Django 3.1.4 on 2021-08-31 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0168_auto_20210831_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='free_settings',
            field=models.IntegerField(default=-1, help_text='Use only if Parc Ferme is used: -1=use RFM/season/GDB default, or add to allow minor changes with fixed\\/parc ferme setups: 1=steering lock, 2=brake pressure, 4=starting fuel, 8=fuel strategy 16=tire compound, 32=brake bias, 64=front wing, 128=engine settings', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_type',
            field=models.CharField(choices=[('0', 'Standing start'), ('1', 'Formation Lap and standing start'), ('2', 'Lap behind safety car & rolling start'), ('4', 'Fast rolling start')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='cdaeaiedgddhaihhigge', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
