# Generated by Django 3.1.4 on 2021-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0170_auto_20210831_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='remove_cbash_shaders',
            field=models.BooleanField(default=False, help_text='Decides if APX will remove the content of the folders CBash and shaders'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ebgiabdagciiheeegfdd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
