# Generated by Django 3.1.4 on 2021-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0171_auto_20210903_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesessions',
            name='real_road_time_scale',
            field=models.CharField(choices=[('-1', 'scaled with session length'), ('0', 'static'), ('0.1', '0.1x'), ('0.2', '0.2x'), ('0.3', '0.3x'), ('0.4', '0.4x'), ('0.5', '0.5x'), ('0.6', '0.6x'), ('0.7', '0.7x'), ('0.8', '0.8x'), ('0.9', '0.9x'), ('1', 'normal'), ('1.5', '1.5x'), ('2', '2x'), ('3', '3x'), ('4', '4x'), ('5', '5x'), ('6', '6x'), ('7', '7x'), ('8', '8x'), ('9', '9x'), ('10', '10x'), ('11', '11x'), ('12', '12x'), ('13', '13x'), ('14', '14x'), ('15', '15x')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ccfggfdidfeihihbhbaf', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='remove_cbash_shaders',
            field=models.BooleanField(default=False, help_text='Decides if APX will remove the content of the folders CBash and shaders. Use with caution.', verbose_name='remove Cbash and Shaders folder'),
        ),
    ]
