# Generated by Django 3.1.4 on 2021-09-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0173_auto_20210903_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deny_ai_voting',
            field=models.BooleanField(default=False, help_text='Disable any voting to add AI cars'),
        ),
        migrations.AddField(
            model_name='event',
            name='deny_other_voting',
            field=models.BooleanField(default=False, help_text='Disable any other voting'),
        ),
        migrations.AddField(
            model_name='event',
            name='deny_session_voting',
            field=models.BooleanField(default=False, help_text='Disable any voting to switch sessions'),
        ),
        migrations.AlterField(
            model_name='racesessions',
            name='grip_needle',
            field=models.CharField(blank=True, default=None, help_text="If you want to use the mod provided grip, add a filename/ and or part of the rrbin filename. You can also add 'autosave' to use the autosave file, which must be existing (also keep settings folder in the server options). If found, the uploaded grip file will be ignored.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='geacfbhbaeighhecfebb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
