# Generated by Django 3.1.4 on 2021-09-04 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0175_auto_20210903_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_strength',
            field=models.IntegerField(default=100, help_text='AI Driver Strength', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='racesessions',
            name='grip_needle',
            field=models.CharField(blank=True, default=None, help_text="If you want to use the mod provided grip, add a filename/ and or part of the rrbin filename. You can also add 'autosave' to use the autosave file, which must be existing (also keep settings folder in the server options). If found, the uploaded grip file will be ignored. You can also use the constants 'natural' or 'green' to define grip levels", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='degcadddiafhfggbefba', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
