# Generated by Django 3.1.4 on 2021-09-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0176_auto_20210904_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='remove_unused_mods',
            field=models.BooleanField(default=False, help_text='Decides if APX will remove workshop items downloaded within steamcmd, but not used for the deployment. ', verbose_name='remove unused workshop items'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='geecbgabdbbbgbdfhcfd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
