# Generated by Django 3.1.4 on 2021-09-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0178_auto_20210911_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='ignore_warnings',
            field=models.BooleanField(default=False, help_text='Ignore warnings at validation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='skip_all_session_unless_configured',
            field=models.BooleanField(default=False, help_text='Instead of using default values from the player.JSON/ multiplayer.JSON, skip all sessions unless the ones configured with the conditions pack in APX.'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='hfaiihhcbcdecfhghfdb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
