# Generated by Django 3.1.4 on 2021-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0179_auto_20210911_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesessions',
            name='race_finish_criteria',
            field=models.CharField(blank=True, choices=[('-2', '%laps'), ('-1', '%time'), ('0', '%laps&time'), ('1', 'laps'), ('2', 'time'), ('3', 'laps&time')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='racesessions',
            name='start',
            field=models.TimeField(blank=True, default=None, help_text='Target laps for this session. This is in-game time. If empty, the defaults will be used.', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='iccbeeehhaecidagggae', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
