# Generated by Django 3.1.4 on 2021-09-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0181_auto_20210912_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceconditions',
            options={'verbose_name': 'Race weekend'},
        ),
        migrations.AddField(
            model_name='event',
            name='forced_driving_view',
            field=models.CharField(choices=[('0', 'no restrictions on driving view'), ('1', 'cockpit\\/tv cockpit\\/nosecam only'), ('3', 'cockpit only'), ('4', 'tracksides'), ('5', 'tracksides group 1')], default='0', help_text='Enforce a certain view for clients', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='conditions',
            field=models.ForeignKey(help_text='Conditions is a bundle of session definitions, containing session lengths and grip information.', on_delete=django.db.models.deletion.CASCADE, to='webgui.raceconditions', verbose_name='race weekend'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='aehabchgcefdhcdagiaf', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
