# Generated by Django 3.1.4 on 2021-09-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0183_auto_20210919_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='base_class',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='dgbcadaacaifgdfbbefc', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
