# Generated by Django 3.1.4 on 2021-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0184_auto_20210919_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='base_class',
            field=models.CharField(blank=True, default=None, help_text="On which class is the car based? If empty, APX will pick the first car as a basis. If the mod does not have multiple classes, you don't need this.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_components',
            field=models.ManyToManyField(blank=True, help_text='Cars allowed to be used. If no entries are existing, all available entries from the mod will be used.', to='webgui.Component', verbose_name='Cars'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gacffibgiedabbbhfdci', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
