# Generated by Django 3.1.4 on 2021-09-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0185_auto_20210925_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='difhdbbhiabacbfeacbb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
