# Generated by Django 3.1.4 on 2021-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0186_auto_20210925_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='heartbeat_only',
            field=models.BooleanField(default=False, help_text='Tells the reciever instance to only include status updates as ticker messages'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='base_class',
            field=models.CharField(blank=True, default=None, help_text='If no component template is used, name the class of the car suitable to be used as a base. Otherwise the first veh file will be used.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='afeeiaigdbedefdbifec', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
