# Generated by Django 3.1.4 on 2021-10-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0187_auto_20211001_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='heartbeat_only',
            field=models.BooleanField(default=True, help_text='Tells the reciever instance to only include status updates as ticker messages'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='daigfegefahcccbbfdbi', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
