# Generated by Django 3.1.4 on 2021-10-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0191_auto_20211002_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='servercron',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Modifier'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='ccgdiaaggfgbcdgehfaa', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='servercron',
            name='modifier',
            field=models.IntegerField(default=1, help_text='Repeat the job each X minutes'),
        ),
    ]
