# Generated by Django 3.1.4 on 2021-10-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0196_auto_20211003_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='base_steam_id',
            field=models.BigIntegerField(blank=True, default=0, help_text='If this mod is based on a nother steam workshop item, name it here'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='hfhcdgiibgadgdcacacg', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='serverplugin',
            name='plugin_path',
            field=models.CharField(blank=True, default=None, help_text='The target folder the file should be placed into. Seen relative from the rFactor 2 server root folder', max_length=500, null=True),
        ),
    ]
