# Generated by Django 3.1.4 on 2021-10-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0197_auto_20211008_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='base_steam_id',
        ),
        migrations.AddField(
            model_name='component',
            name='base_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webgui.component'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='fbfffgbbigicfdbbdbie', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
