# Generated by Django 3.1.4 on 2021-10-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0198_auto_20211008_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='alternative_name',
            field=models.CharField(blank=True, default=None, help_text='Alternative display name to keep same mods with different components apart', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='efaiacecfhecigghahih', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
