# Generated by Django 3.1.4 on 2021-10-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0200_auto_20211009_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Livery', 'verbose_name_plural': 'Liveries'},
        ),
        migrations.RemoveField(
            model_name='server',
            name='state',
        ),
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
        migrations.AlterField(
            model_name='event',
            name='entries',
            field=models.ManyToManyField(blank=True, to='webgui.Entry', verbose_name='Liveries'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='heaiacaibgedbbcefecd', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
