# Generated by Django 3.1.4 on 2021-10-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0201_auto_20211011_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='discord_url',
            field=models.CharField(blank=True, default='', help_text='An alternative webhook URL to be used instead of the DISCORD_WEBHOOK setting', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='gfeedfadegdcfeeddifb', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
