# Generated by Django 3.1.4 on 2021-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0203_auto_20211016_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='force_versions',
            field=models.CharField(choices=[('0', 'Use the versions as user provided'), ('1', 'Try to guess versions for mods having an encrypted base mod and an update version (e. g. paid DLC)'), ('2', 'Same as second option, but use the scheme also for mods without an encrypted base mod')], default='0', help_text='Versioning scheme', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='real_weather',
            field=models.BooleanField(default=False, help_text='Decides if real weather should be used. This will be using https://forum.studio-397.com/index.php?threads/weatherplugin.58614/ in the background.'),
        ),
        migrations.AlterField(
            model_name='server',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Update config and redeploy'), ('D+F', 'Update config and redeploy, force content re-installation'), ('W', 'Restart weekend'), ('WU', 'Weather forecast update')], default='', help_text='Runs an activity on the server.', max_length=3, verbose_name='Pending action to submit'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='fhsvathfngnsqxhiizgy', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.AlterField(
            model_name='servercron',
            name='action',
            field=models.CharField(blank=True, choices=[('S+', 'Start'), ('R-', 'Stop'), ('D', 'Update config and redeploy'), ('D+F', 'Update config and redeploy, force content re-installation'), ('W', 'Restart weekend'), ('WU', 'Weather forecast update')], default='', help_text='Runs an activity on the server.', max_length=3, verbose_name='Pending action to submit'),
        ),
    ]
