# Generated by Django 3.1.4 on 2022-01-02 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0205_auto_20211219_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ignore_updates_hook',
            field=models.BooleanField(default=True, help_text="Don't fire the Discord messages when the server was updated"),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='watwlqzopmmxjdvzwrpi', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webgui.server')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(default=0)),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(max_length=255)),
                ('laps', models.IntegerField(default=0)),
                ('stops', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('class_name', models.CharField(max_length=255)),
                ('is_pitting', models.BooleanField(default=False)),
                ('in_garage', models.BooleanField(default=False)),
                ('steam_id', models.CharField(max_length=255)),
                ('under_yellow', models.BooleanField(default=False)),
                ('timetable', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webgui.timetable')),
            ],
        ),
    ]
