# Generated by Django 3.1.4 on 2022-02-14 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0205_auto_20211219_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='multiplayer_overwrites',
            field=models.TextField(default='{}', help_text='Additional multiplayer.JSON overwrites.'),
        ),
        migrations.AddField(
            model_name='event',
            name='player_overwrites',
            field=models.TextField(default='{}', help_text='Additional player.JSON overwrites.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='free_settings',
            field=models.IntegerField(default=-1, help_text='Use only if Parc Ferme is used: -1=use RFM/season/GDB default, or add to allow minor changes with fixed/parc ferme setups: 1=steering lock, 2=brake pressure, 4=starting fuel, 8=fuel strategy 16=tire compound, 32=brake bias, 64=front wing, 128=engine settings', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='ignore_updates_hook',
            field=models.BooleanField(default=True, help_text="Don't fire the Discord messages when the server was updated"),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='komevjjuovjetofbhvoz', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
