# Generated by Django 3.1.4 on 2022-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0206_auto_20220215_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='multiplayer_overwrites',
            field=models.TextField(blank=True, default='{}', help_text='Additional multiplayer.JSON overwrites.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='player_overwrites',
            field=models.TextField(blank=True, default='{}', help_text='Additional player.JSON overwrites.'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='wxgoausfqhbjpiimapgg', help_text='The secret for the communication with the APX race control', max_length=500),
        ),
    ]
