# Generated by Django 3.2.13 on 2022-06-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0208_auto_20220604_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='update_weather_on_start',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='tbfiarwwaivrncatfngv', help_text='Used for internal purposes.', max_length=500),
        ),
    ]
