# Generated by Django 3.2.13 on 2022-06-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0209_auto_20220604_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racesessions',
            name='weather',
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='pnirmrchwkujaruqgiyi', help_text='Used for internal purposes.', max_length=500),
        ),
    ]
