# Generated by Django 3.2.13 on 2022-06-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0211_auto_20220605_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='message',
            field=models.CharField(blank=True, default=None, help_text="Submits a message or a command to the given server. Can't be longer than 50 chars", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_secret',
            field=models.CharField(blank=True, default='bjseadknipynprnagqtg', help_text='Used for internal purposes.', max_length=500),
        ),
    ]
