# Generated by Django 3.2.13 on 2022-06-06 06:45

from django.db import migrations, models
import webgui.util


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0214_raceconditions_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fixed_setup',
            field=models.FileField(blank=True, default=None, help_text='A fixed setup to use on the server', null=True, upload_to=webgui.util.get_conditions_file_root, verbose_name='Fixed setup'),
        ),
        migrations.AddField(
            model_name='event',
            name='fixed_setups',
            field=models.BooleanField(default=False, help_text='Enforce to use fixed setups'),
        ),
        migrations.AlterField(
            model_name='raceconditions',
            name='settings',
            field=models.TextField(blank=True, default=None, help_text='See https://wiki.apx.chmr.eu/doku.php?id=rfm_settings for details', null=True),
        ),
    ]
