# Generated by Django 3.2.13 on 2022-06-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0215_auto_20220606_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fixed_setup',
        ),
        migrations.AlterField(
            model_name='event',
            name='fixed_setups',
            field=models.BooleanField(default=False, help_text='Enforce to use fixed setups. You might need to use this to enforce a Parc Ferme setting even without uploading a fixed setup.'),
        ),
    ]
