# Generated by Django 3.2.13 on 2022-06-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0217_rename_serverplugin_serverfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='plugins',
            new_name='files',
        ),
    ]
