# Generated by Django 3.2.13 on 2022-06-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0218_rename_plugins_event_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverfile',
            old_name='plugin_path',
            new_name='target_file_path',
        ),
    ]
