# Generated by Django 3.2.13 on 2022-06-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0219_rename_plugin_path_serverfile_target_file_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaceConditions',
            new_name='RaceWeekend',
        ),
    ]
